version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: dev,test
    volumes:
      - ./db:/var/lib/postgresql/dev
      - ./init_dbs.sh:/docker-entrypoint-initdb.d/init_dbs.sh
    ports:
      - "5432:5432"
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=200", "-c", "listen_addresses=*"]
    restart: unless-stopped
